name: Release And Deploy

# Controls when the workflow will run
on:
  pull_request:
    types: [ closed ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  packages: write
  contents: write
  issues: write
  id-token: write
  actions: read


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push
        uses: pagopa/github-actions-template/ghcr-build-push@v1.6.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: 1.0.0
